[package]
name = "razer-sdk-reader-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.26.2"
rand = "0.9.0-alpha.1"
lazy_static = "1.4.0"

[dependencies.windows]
version = "0.54.0"
features = [
    "Win32",
    "Win32_Security",
    "Win32_Foundation",
    "Win32_System_Threading",
    "Win32_System_SystemServices",
    "Win32_System_Memory_NonVolatile",
]