[package]
name = "razer-sdk-reader-rs"
version = "0.1.0"
edition = "2021"

[dependencies]

[dependencies.windows]
version = "0.54.0"
features = [
    "Win32",
    "Win32_Security",
    "Win32_Foundation",
    "Win32_System_Threading",
    "Win32_System_SystemServices",
    "Win32_System_Memory_NonVolatile",
]